### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by maziarz** [continuon/vue-intercom#4]
Finally the site is in production and i have this funny one here:

```
TypeError: Cannot read property 'apply' of undefined
  at f(./node_modules/vue-intercom/dist/vue-intercom.js:46:26)
  at ? (./node_modules/vue-intercom/dist/vue-intercom.js:60:34)
  at Array.forEach(/en)
  at _init(./node_modules/vue-intercom/dist/vue-intercom.js:60:1)
  at HTMLScriptElement.<anonymous>(./node_modules/vue-intercom/dist/vue-intercom.js:110:49)
```

Browser: Opera Version: 22.0.1471
OS: Windows 8.1

Is it a Opera thing by any chance?

**Comment by maziarz** [comment]
I am running Sentry. I got 35 events on this issue from 20 different user. 

Here are the system combinations:

Windows 7
Chrome 41.0.2228

Windows 7
Chrome 61.0.3163

Windows Phone 8.1
IE Mobile 11.0

Windows 10
Chrome 61.0.3163

Windows 10
Firefox 56.0

Windows 10
Edge 15.15063

Android 5.1.1
Chrome Mobile 38.0.2125

iOS 11.0.2
Mobile Safari 11.0

So we can conclude its a general issue.

Basically i am calling`this.$intercom.boot()` in mounted of my default layout:

`layouts/default.vue`

<template lang="pug">
div
  nuxt
</template>

<script>
export default {
  mounted: function () {
    this.$intercom.boot()
  }
}
</script>

`plugins/vue-intercom.js`

```
import Vue from 'vue'
import VueIntercom from 'vue-intercom'

Vue.use(VueIntercom, { appId: 'XXXX' })
```

Please keep in mind that i use nuxt.js

**Comment by johnnynotsolucky** [comment]
It might be a regression to #1, i.e. and ad blocker of some sort. I can reproduce the problem if I load a script which doesn't set `window.Intercom`, but I haven't been able to find an ad blocker which implements that sort of behaviour. 

Another possibility which I haven't been able to replicate would be that there is a race condition between the Intercom script loading, and it setting `window.Intercom`.

I think a interim solution might be to make sure Intercom is available before calling `_init` instead of _only_ waiting for the script to load.

**Comment by johnnynotsolucky** [comment]
Intercom gives us the ability to add a temporary placeholder on `window`, see https://docs.intercom.com/install-on-your-product-or-site/other-ways-to-get-started/integrate-intercom-in-a-single-page-app. I've reverted previous changes to hold calls until Intercom function is ready and implemented something similar to the script in the link.

**Comment by maziarz** [comment]
Excellent!
