### ISSUE TITLE
Documentation for prerendering/SSR?

### ISSUE THREAD

**Issue by philipithomas** [continuon/vue-intercom#5]
It seems that the intercom script tries to fire before the DOM has been loaded / before Vue has mounted when doing prerendering:

> Uncaught TypeError: Cannot read property 'appendChild' of null

Any ideas of how to prevent this?

**Comment by johnnynotsolucky** [comment]
I’m not really familiar with SSR, but I think the script can be loaded in the mounted hook like you mentioned. The DOM is available at that point. If I used the vue-pwa template would I be able to replicate the issue?

**Comment by philipithomas** [comment]
It turns out I was trying to load Intercom in the rendering. So, if you can detect it and not load it, that is one fix. Another is to set the user-agent of the service doing rendering to `crawler`, because Intercom doesn't load for crawlers. 

To test this - I suggest sticking Vue on Netlify.

**Comment by philipithomas** [comment]
I think one of the issues is that, after intercom is loaded, it only preserves the loading of the widget js, which assumes that the body has already been loaded.

**Comment by johnnynotsolucky** [comment]
I've made an update to load the script in the `mounted()` hook instead of `created()`.

From the [Vue.js SSR docs](https://ssr.vuejs.org/en/universal.html#component-lifecycle-hooks):

> Since there are no dynamic updates, of all the lifecycle hooks, only beforeCreate and created will be called during SSR. This means any code inside other lifecycle hooks such as beforeMount or mounted will only be executed on the client.

I tested the changes in the the [vue-hackernews-2.0](https://github.com/vuejs/vue-hackernews-2.0) project too and confirm that the script is only loaded on the client side, and no longer rendered server-side.

If this change still doesn't fix the issue, could you share some of your set up so I can try replicate it on my side?
